function [accuracy, treshold] = Func_Accuracy(mu, sigma, r)
    e = exp(1);
    treshold = 1/2*(sigma(1)^2 - sigma(2)^2) * ...
        (-2 * mu(1) * sigma(2)^2 + 2 * mu(2) * sigma(1)^2 - ...
        sqrt((2 * mu(2) * sigma(1)^2 - 2 * mu(1) * sigma(2)^2)^2 ...
        + 4 * sigma(1)^2 * (sigma(2)^2 - sigma(1)^2) * ...
        (mu(2)^2 + sigma(2)^2 * log(-1 * sigma(2) * ((r * e ^ (-1 * mu(1)^2/sigma(1)^2)) / sigma(1) ...
        - (e ^ (-1*mu(1)^2/sigma(1)^2)/sigma(1)) / r)))));
    treshold = (treshold + conj(treshold))/2;
    accuracy = 1 - (normcdf(treshold, mu(1), sigma(1)) * (1 - r) + ...
        (1 - normcdf(treshold, mu(2), sigma(2))) * r);
end

